### DISCUSSION TITLE
Usage of same property as DynamoDBRangeKey and DynamoDBGlobalSecondaryIndexHashKey

### DISCUSSION THREAD

**Discussion by maaaxk** [aws/aws-sdk-net#3232] [Q&A] [answered]
Greetings to AWS community,

In our project DynamoDb table is configured (**cf below**) in such a way that one of the properties (e.g. TransactionId) is defined as both
 - DynamoDBRangeKey (making part of a composite primary key together with Id) 
 - GlobalSecondaryIndex (as a HashKey)

The table was successfully created and both Queries (via partition primary key and GSI) are available and working as expected via UI and in our solution written in .NET using AWSSDK.DynamoDBv2.

Meanwhile, in the appropriate DynamoModel described in our code (**code below**) there is no DynamoDBRangeKey annotation applied to "TransactionId" property, and only DynamoDBGlobalSecondaryIndexHashKey is applied. 

So the question is why it is working and allows us to call both methods:
 - Task<T> LoadAsync<T>(object hashKey, object rangeKey, CancellationToken cancellationToken = default(CancellationToken)); - using composite primary key
 -  AsyncSearch<T> QueryAsync<T>(object hashKeyValue, DynamoDBOperationConfig operationConfig = null); - using GSI

**DynamoDb Cf**
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Dynamo db resources
Parameters: 
  EnvironmentName:
    Type: String
    MinLength: '1'
    AllowedPattern: '[a-zA-Z0-9]*'
Resources:
  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: TransactionId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-Order
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
        - AttributeName: TransactionId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: "TransactionIdIndex"
          KeySchema: 
            - AttributeName: "TransactionId"
              KeyType: "HASH"
          Projection: 
            ProjectionType: "ALL"
```

**DynamoDbModel class**
 
```
    [DynamoDBTable("Order")]
    public class OrderDynamoModel
    {
        [DynamoDBHashKey]
        public string Id { get; set; }
        
        [DynamoDBGlobalSecondaryIndexHashKey("TransactionIdIndex")]
        public string TransactionId { get; set; }
		
        public string ProductCode { get; set; }
		
        public string PaymentStatus { get; set; }

        [DynamoDBVersion]
        public int? VersionNumber { get; set; }
    }
```

Thank you in advance!
