### ISSUE TITLE
Using EKS IAM for Service Accounts Requires Calling AddDefaultAWSOptions

### ISSUE THREAD

**Issue by bliles** [aws/aws-sdk-net#1731]
## Description
When using the EC2 metadata service to configure AWSSDK credentials, no configuration is necessary. You can simply instantiate a client and begin using it. In contrast, when using EKS IAM for Service Accounts, although all of the necessary configuration is present in the environment, it is necessary to call AddDefaultAWSOptions, I believe to set the AWS region. This is the case even if the environment contains the AWS_REGION parameter.

## Reproduction Steps
Under an EKS IAM for Service Accounts environment, create an SDK client and attempt to use it without calling AddDefaultAWSOptions. You will get a NullReferenceException from Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.GenerateNewCredentials. I believe this is due to the fact that here: https://github.com/aws/aws-sdk-net/blob/aws-sdk-net-v3.3/sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleAWSCredentials.cs#L92 you are referencing AWSConfigs.AWSRegion before this property has been set.

### Logs
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.GenerateNewCredentials()
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentials()
   at Amazon.S3.AmazonS3Client.GetPreSignedURLInternal(GetPreSignedUrlRequest request, Boolean useSigV2Fallback)
   at Amazon.S3.Util.AmazonS3Util.DoesS3BucketExistAsync(IAmazonS3 s3Client, String bucketName)
   at ...
```

### Environment

* SDK Version: Was not able to determine how to map between nuget package versions and the SDK version (another thing that could be more clear about this project)
* Package Version: AWSSDK.Core 3.3.107.40, AWSSDK.S3 3.3.113.2
* OS Info: mcr.microsoft.com/dotnet/core/aspnet:3.1 linux docker container running in EKS
* Build Environment: Multistage docker build using mcr.microsoft.com/dotnet/core/sdk:3.1
* Targeted .NET Platform: .NET Core 3.1

## Resolution
I found that adding this in the Startup:ConfigureServices method avoided the problem, but it seems unnecessary since all the needed configuration is already available in the environment:
```csharp
services.AddDefaultAWSOptions(
    new Amazon.Extensions.NETCore.Setup.AWSOptions(){
        Region = RegionEndpoint.GetBySystemName(Environment.GetEnvironmentVariable("AWS_REGION"))
    }
);
```

It would be nice if the SDK worked without any configuration when using EKS IAM for Service Accounts just as it does with the EC2 metadata service.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @bliles, 

Good morning.

Thanks for reporting the issue. I do see that your application is running in a Linux Docker container in EKS. Please let me know how are environment variables passed to Docker container. It would also be helpful if you could share the sample code and the deployment steps that you followed, this would he helpful in issue reproduction.

Regards,
Ashish

**Comment by bliles** [comment]
Hi Ashish,

This sample Program.cs is sufficient to see the issue:

```csharp
using Amazon;
using Amazon.S3;
using System;
using System.Threading.Tasks;

namespace DotnetSample
{
    class Program
    {
        async static Task Main(string[] args)
        {
            var client = new AmazonS3Client();
            var results = await client.ListBucketsAsync();
            foreach(var bucket in results.Buckets) {
                Console.WriteLine(bucket.BucketName);
            }
        }
    }
}
```

If you run this in a EKS cluster with EKS IAM for Service Accounts correctly configured, you will get the NullReferenceException I mentioned. If instead you ran this on an EC2 instance that has an IAM profile with s3:listbuckets permissions, it will work.

This is an example pod manifest under EKS pulled from here: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/. The one adjustment is we are adding the AWS_REGION env var.
```yaml
apiVersion: apps/v1
kind: Pod
metadata:
  name: myapp
spec:
  serviceAccountName: my-serviceaccount
  containers:
  - name: myapp
    image: myapp:1.2
    env:
    - name: AWS_REGION
      value: us-east-1
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::123456789012:role/eksctl-irptest-addon-iamsa-default-my-serviceaccount-Role1-UCGG6NDYZ3UE
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    volumeMounts:
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
```
