### ISSUE TITLE
AWS_STS_REGIONAL_ENDPOINTS as environmental variables

### ISSUE THREAD

**Issue by h-c-a** [aws/aws-sdk-net#1856]
## Description
setting AWS_STS_REGIONAL_ENDPOINTS with a value regional, still makes use of `us-east-1` instead of `ap-south-1`

## Reproduction Steps
1) Deployed pods in EKS (`ap-south-1`) , with environmental variable `AWS_REGION` and `AWS_DEFAULT_REGION` set to  `ap-south-1`
2) AWS_STS_REGIONAL_ENDPOINTS is set to value `Regional`

### Environment
* SDK Version:  AWSSDK.SecurityToken 
* Package Version: 3.7.0, 3.7.1.17
* OS Info: Ubuntu 
* Build Environment: Terminal `dotnet` 
* Targeted .NET Platform:  

## Resolution
- [ ] :wave: I would-like-to ensure that a STS call is made to sts.ap-south-1.amazonaws.com based on ensuring regional endpoints are activated

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html

additional info:

![image](https://user-images.githubusercontent.com/1141897/118969016-dff64f80-b96c-11eb-9652-33f3ce2c9238.png)

![image](https://user-images.githubusercontent.com/1141897/118969136-01573b80-b96d-11eb-93dc-2ee791882cdb.png)

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @h-c-a,

Good morning.

Could you please provide the details steps and sample code to reproduce the issue? Screenshots doesn't appear to be helpful.

Thanks,
Ashish

**Comment by h-c-a** [comment]
hi @ashishdhingra 

sorry it took a while to reproduce the issue.

**Code Sample**

 ```csharp
using System;
using System.Threading.Tasks;
using Amazon;
using Amazon.S3;

namespace OidcChecker
{
    class Program
    {
        static async Task Main(string[] args)
        {
            AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;
            AWSConfigs.LoggingConfig.LogMetrics = true;
            AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.Always;
            AWSConfigs.LoggingConfig.LogMetricsFormat = LogMetricsFormatOption.JSON;

            Environment.SetEnvironmentVariable("AWS_DEFAULT_REGION", "ap-south-1");
            Environment.SetEnvironmentVariable("AWS_REGION", "ap-south-1");
            Environment.SetEnvironmentVariable("AWS_STS_REGIONAL_ENDPOINTS", "regional");
            Environment.GetEnvironmentVariable("AWS_ROLE_ARN");
            Environment.GetEnvironmentVariable("AWS_WEB_IDENTITY_TOKEN_FILE");

            if (string.IsNullOrEmpty(Environment.GetEnvironmentVariable("AWS_ROLE_ARN")))
            {
                throw new Exception("failed to load AWS_ROLE_ARN");
            };
            if (string.IsNullOrEmpty(Environment.GetEnvironmentVariable("AWS_WEB_IDENTITY_TOKEN_FILE")))
            {
                throw new Exception("failed to load AWS_WEB_IDENTITY_TOKEN_FILE");
            }
          
            Console.WriteLine("#######################################################");
            Console.WriteLine("list S3 buckets");
            Console.WriteLine("#######################################################"); 
            
            var s3Client = new AmazonS3Client();
            var s3Results = await s3Client.ListBucketsAsync();
            foreach(var bucket in s3Results.Buckets) {
                Console.WriteLine(bucket.BucketName);
            }           
            
            Console.ReadLine();
        }
    }
}
```


**Logs**

```javascript
AmazonSecurityTokenServiceClient 8|2021-05-27T18:05:30.890Z|INFO|Request metrics: {"properties":{"AsyncCall":"True","ServiceName":"Amazon.SecurityToken","ServiceEndpoint":"https://sts.us-east-1.amazonaws.com/","MethodName":"AssumeRoleWithWebIdentityRequest","RequestSize":"1210","StatusCode":"OK","BytesProcessed":"2341","AWSRequestID":"f5fc9626-f10b-4380-8233-28aabcccff43"},"timings":{"HttpRequestTime":2405.3495000000003,"ResponseUnmarshallTime":23.244200000000003,"ResponseProcessingTime":30.7632,"ClientExecuteTime":2492.3585000000003},"counters":{}}
```


as you can see from the log, its seems to use `https://sts.us-east-1.amazonaws.com` service although the `AWS_DEFAULT_REGION` and `AWS_REGION` is set to `ap-south-1` and `AWS_STS_REGIONAL_ENDPOINTS` is set to `regional`


This a issue for us as the response time of each call adds 2 to 3 seconds on average ("HttpRequestTime":2405.3495000000003)

i have attached the full log, with sensitive info redacted.

[oidcchecker-594db79947-fw65c.log](https://github.com/aws/aws-sdk-net/files/6555982/oidcchecker-594db79947-fw65c.log)

**Comment by juniortads** [comment]
Hi @h-c-a,  I have been having the same problem here. First I tried set env var following this documentation https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-sts_regional_endpoints.html but check the SDK code, I realised that when the SDK creates the client it considers `var configuredRegion = AWSConfigs.AWSRegion;` I tested with your **code sample** adding AWSRegion and that works for me.

`AWSConfigs.AWSRegion = "ap-south-1"`

Let me know please that works for you.

**Comment by masteredward** [comment]
Thanks @juniortads. It worked for me. I was struggling with this issue for months. I have tested it in a private EKS cluster with endpoints only. Also i have added the AWS_STS_REGIONAL_ENDPOINTS=regional environment to the pod spec instead of adding it to the code.

**Comment by h-c-a** [comment]
> Hi @h-c-a, I have been having the same problem here. First I tried set env var following this documentation https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-sts_regional_endpoints.html but check the SDK code, I realised that when the SDK creates the client it considers `var configuredRegion = AWSConfigs.AWSRegion;` I tested with your **code sample** adding AWSRegion and that works for me.
> 
> `AWSConfigs.AWSRegion = "ap-south-1"`
> 
> Let me know please that works for you.

It works, thanks.

but the reason I add this issue, is because it does not respect the `AWS_STS_REGIONAL_ENDPOINTS` and the `AWS_REGION`, needing me to add the work around in code :) 

we run in multi region setups, making it annoying to maintain ` AWSConfigs.AWSRegion`  in code.

**Comment by ashishdhingra** [comment]
@h-c-a One quick question, are you using Windows pods or Amazon Linux 2 pods in EKS?

**Comment by ashishdhingra** [comment]
Issue reproducible, here is the STS call from logs:
```
AmazonSecurityTokenServiceClient 10|2021-08-27T23:41:25.634Z|INFO|Request metrics: {"properties":{"AsyncCall":"True","ServiceName":"Amazon.SecurityToken","ServiceEndpoint":"https://sts.us-east-1.amazonaws.com/","MethodName":"AssumeRoleWithWebIdentityRequest","RequestSize":"1301","StatusCode":"OK","BytesProcessed":"2426","AWSRequestID":"deaa7fcb-fc85-4026-8f3f-045e35e5210c"},"timings":{"HttpRequestTime":2129.7092,"ResponseUnmarshallTime":17.2823,"ResponseProcessingTime":22.8095,"ClientExecuteTime":2185.4172},"counters":{}}
```

**Reproduction Steps:**
1. Create a .NET Core Console application targeting .NET Core 3.1. Create the below `Dockerfile`, `eks-cluster-create.yaml` and `eks-manifest.yaml`.
**.csproj file**
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerComposeProjectPath>../docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AWSSDK.S3" />
    <None Remove="AWSSDK.SecurityToken" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.1.26" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="3.7.1.46" />
  </ItemGroup>
</Project>
```
**Program.cs**
```C#
using System;
using System.Threading.Tasks;
using Amazon;
using Amazon.S3;

namespace EKSTest_Issue1856
{
    class Program
    {
        static async Task Main(string[] args)
        {
            AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;
            AWSConfigs.LoggingConfig.LogMetrics = true;
            AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.Always;
            AWSConfigs.LoggingConfig.LogMetricsFormat = LogMetricsFormatOption.JSON;

            Environment.SetEnvironmentVariable("AWS_DEFAULT_REGION", "ap-south-1");
            Environment.SetEnvironmentVariable("AWS_REGION", "ap-south-1");
            Environment.SetEnvironmentVariable("AWS_STS_REGIONAL_ENDPOINTS", "regional");
            Environment.GetEnvironmentVariable("AWS_ROLE_ARN");
            Environment.GetEnvironmentVariable("AWS_WEB_IDENTITY_TOKEN_FILE");

            if (string.IsNullOrEmpty(Environment.GetEnvironmentVariable("AWS_ROLE_ARN")))
            {
                throw new Exception("failed to load AWS_ROLE_ARN");
            };
            if (string.IsNullOrEmpty(Environment.GetEnvironmentVariable("AWS_WEB_IDENTITY_TOKEN_FILE")))
            {
                throw new Exception("failed to load AWS_WEB_IDENTITY_TOKEN_FILE");
            }

            Console.WriteLine("#######################################################");
            Console.WriteLine("list S3 buckets");
            Console.WriteLine("#######################################################");

            var s3Client = new AmazonS3Client();
            var s3Results = await s3Client.ListBucketsAsync();
            foreach (var bucket in s3Results.Buckets)
            {
                Console.WriteLine(bucket.BucketName);
            }

            Console.ReadLine();
        }
    }
}
```
**Dockerfile**
```
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["EKSTest_Issue1856.csproj", "EKSTest_Issue1856/"]
RUN dotnet restore "EKSTest_Issue1856/EKSTest_Issue1856.csproj"
COPY . EKSTest_Issue1856/
WORKDIR "/src/EKSTest_Issue1856"
RUN dotnet build "EKSTest_Issue1856.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EKSTest_Issue1856.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EKSTest_Issue1856.dll"]
```
**eks-cluster-create.yaml**
```YAML
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-issue1856
  region: ap-south-1
  version: "1.20"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: eks-issue1856-s3-reader
      # if no namespace is set, "default" will be used;
      # the namespace will be created if it doesn't exist already
      namespace: eks-issue1856-ns
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
  - metadata:
      name: eks-issue1856-ecr-access
      namespace: eks-issue1856-ns
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true
    roleName: eksctl-cluster-autoscaler-role
    roleOnly: true
  
nodeGroups:
  - name: "ng-1"
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-13: "owned"
    desiredCapacity: 1
```
**eks-manifest.yaml**
```YAML
apiVersion: apps/v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      Process: eks-issue1856
    creationTimestamp: null
    labels:
      app: eks-issue1856
    name: eks-issue1856
  spec:
    type: LoadBalancer
    ports:
    - name: "5999"
      port: 5999
      targetPort: 5999
    selector:
      app: eks-issue1856
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: eks-issue1856
    namespace: eks-issue1856-ns
  spec:
    selector:
      matchLabels:
        app: eks-issue1856
    replicas: 1
    template:
      metadata:
        labels:
          app: eks-issue1856
      spec:
        serviceAccountName: eks-issue1856-s3-reader
        containers:
        - name: eks-issue1856
          image: <<accountid>>.dkr.ecr.ap-south-1.amazonaws.com/eksissue1856:latest
          ports:
          imagePullPolicy: Always #IfNotPresent
        restartPolicy: Always
kind: List
metadata: {}
```
_NOTE:_ Replace `<<accountid>>` in above `eks-manifest.yaml` with your own account ID. Kindly note that `image` should be set to ECR image created in step 3 below.

2. Create the ECR repository from AWS Console. Take note of the Push commands.
3. From the project root directory, execute the push commands one by one:
- - `aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin <<accountid>>.dkr.ecr.ap-south-1.amazonaws.com`
- - `docker build -t eksissue1856 .`
- - `docker tag eksissue1856:latest <<accountid>>.dkr.ecr.ap-south-1.amazonaws.com/eksissue1856:latest`
- - `docker push <<accountid>>.dkr.ecr.ap-south-1.amazonaws.com/eksissue1856:latest`
4. From the project root directory, execute the command `eksctl create cluster --config-file=./eks-cluster-create.yaml` to create EKS cluster. This will use configuration in YAML file to create EKS cluster, IAM OIDC provider, required service account(s) and node group(s).
5. From project root directory, execute `kubectl apply -f ./eks-manifest.yaml` (to delete deployment, you may use `kubectl delete -f ./eks-manifest.yaml` command).
6. After the `eks-issue1856` workload is created in cluster, click on it and take note of the Pod name. You may examine the pod status by clicking on it (it should be in Running state). (You may also list the pods from command line using command `kubectl get pods --namespace eks-issue1856-ns -o wide`)
7. (You may connect to interactive session using `kubectl exec --stdin --tty --namespace eks-issue1856-ns <<podname>>  -- /bin/bash)`. Replace `eks-issue1856-ns` with your own namespace if differently set in the YAML file. Replace `<<podname>>` with name of pod.)
8. Execute the command `kubectl logs <<podname>> --namespace eks-issue1856-ns` to get the logs (replace `<<podname>>` with name of pod). (Since our console application is the entry point and is writing logs to console, this would give the trace output)
**Log Output:** 
```
#######################################################
list S3 buckets
#######################################################
EnvironmentVariableAWSRegion 1|2021-08-27T23:41:23.278Z|INFO|Region found using environment variable.
EnvironmentVariableInternalConfiguration 2|2021-08-27T23:41:23.333Z|INFO|The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a value.
EnvironmentVariableInternalConfiguration 3|2021-08-27T23:41:23.333Z|INFO|The environment variable AWS_MAX_ATTEMPTS was not set with a value.
EnvironmentVariableInternalConfiguration 4|2021-08-27T23:41:23.333Z|INFO|The environment variable AWS_RETRY_MODE was not set with a value.
EnvironmentVariableInternalConfiguration 5|2021-08-27T23:41:23.334Z|INFO|The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT was not set with a value.
EnvironmentVariableInternalConfiguration 6|2021-08-27T23:41:23.334Z|INFO|The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE was not set with a value.
...
...
AmazonSecurityTokenServiceClient 9|2021-08-27T23:41:25.622Z|DEBUG|Received response (truncated to 1024 bytes): [<AssumeRoleWithWebIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <AssumeRoleWithWebIdentityResult>
    <Audience>sts.amazonaws.com</Audience>
    <AssumedRoleUser>
...
...      
]
AmazonSecurityTokenServiceClient 10|2021-08-27T23:41:25.634Z|INFO|Request metrics: {"properties":{"AsyncCall":"True","ServiceName":"Amazon.SecurityToken","ServiceEndpoint":"https://sts.us-east-1.amazonaws.com/","MethodName":"AssumeRoleWithWebIdentityRequest","RequestSize":"1301","StatusCode":"OK","BytesProcessed":"2426","AWSRequestID":"deaa7fcb-fc85-4026-8f3f-045e35e5210c"},"timings":{"HttpRequestTime":2129.7092,"ResponseUnmarshallTime":17.2823,"ResponseProcessingTime":22.8095,"ClientExecuteTime":2185.4172},"counters":{}}
AssumeRoleWithWebIdentityCredentials 11|2021-08-27T23:41:25.636Z|INFO|New credentials created using assume role with web identity that expire at 2021-08-28T00:41:25.0000000+00:00
AmazonS3Client 12|2021-08-27T23:41:25.704Z|DEBUG|Received response (truncated to 1024 bytes): [<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner>...
...
```
