### ISSUE TITLE
Error when using presigned s3 POST URL: `The AWS Access Key Id you provided does not exist in our records`

### ISSUE THREAD

**Issue by AxelJunker** [aws/aws-sdk-net#1989]
I'm trying to retrieve credentials to create an S3 presigned POST url and it works locally but not when running in ECS. I'm using `Amazon.Runtime.FallbackCredentialsFactory.GetCredentials().GetCredentials()` to retrieve temporary credentials but when trying to upload a file using the url I get:

```
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>ASIA...</AWSAccessKeyId><RequestId>7DQN...</RequestId><HostId>1VW/jng...</HostId></Error>
```

This, however, works:

```fsharp
let s3Client = new AmazonS3Client()

s3Client.GetObjectMetadataAsync("my-bucket", "my-key")
```

...so it seems like the s3 client gets the correct credentials/access.

I have a bucket policy set on my IAM task role:

```yaml
MyBucketPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    ManagedPolicyName: MyBucketPolicy
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: arn:aws:s3:::my-bucket

TaskRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      - !Ref MyBucketPolicy

TaskExecutionRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Task:
  Type: AWS::ECS::TaskDefinition
  Properties:
    ExecutionRoleArn: !GetAtt [TaskExecutionRole, "Arn"]
    TaskRoleArn: !GetAtt [TaskRole, "Arn"]
```

### Environment

* SDK Version: 3
* Package Version: PackageReference Include="AWSSDK.S3" Version="3.7.7.24"
* OS Info: macOS 12.2.1
* Build Environment: Rider + Terminal `dotnet`
* Targeted .NET Platform: dotnet 6, F#
