### ISSUE TITLE
AmazonAPIGatewayClient GetUsagePlanAsync not working (C#) 

### ISSUE THREAD

**Issue by LeonardoX77** [aws/aws-sdk-net#2510]
### Describe the bug

I'm implementing a solution to create AWS Gateway Api Keys.
The basic flow is: 
```
if (CheckUsagePlan(usagePlanId))
    if (!CheckApiKey(customerName))
         return CreateApiKey(parameters);

```

### Expected Behavior

`GetUsagePlanAsync` should return the plan id passed by the parameter

### Current Behavior

`GetUsagePlanAsync` is not returning a plan id which already exists.

### Reproduction Steps

I have configured my credentials in the file C:\Users\userName\\.aws\credentials to reproduce it locally using the [AWS .NET Mock Lambda Test Tool](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool)
```
[default]
region = us-east-1
aws_access_key_id = (some_aws_access_key_id)
aws_secret_access_key = (some_aws_secret_access_key)

```
#
Then write this code
```
        private async Task<bool> CheckUsagePlan(string usagePlanId)
        {
            var apiGatewayClient = new AmazonAPIGatewayClient();
            var p = new GetUsagePlanRequest() { UsagePlanId = usagePlanId };
            var res = await apiGatewayClient.GetUsagePlanAsync(p);

            return res.HttpStatusCode == HttpStatusCode.OK && res.Id == usagePlanId;
        }
```
#
Deploy the solution to aws:
```
sam build
sam deploy 
```

### Possible Solution

The code works ok testing it locally, but it doesn't work once is deployed. 
Also, I've noticed the method `CreateApiKeyAsync` works properly both (locally and remotely), so I think it has to do with the credentials because if I initialize the `AmazonAPIGatewayClient` client this way, the method `GetUsagePlanAsync` works:

```
apiGatewayClient = new AmazonAPIGatewayClient(awsAccessKeyId: "some_aws_access_key_id", awsSecretAccessKey: "some_aws_secret_access_key");
```
But this is not an acceptable solution for obvious reasons. 
The thing is I'm already deploying my solution in "us-east-1" region, so the sdk is able to create an api key just invoking `CreateApiKeyAsync` with a simple name, but as said, it's not able to get a usage plan invoking `GetUsagePlanAsync` with an existing id. Probably there's something missing in the sdk when requesting proper credentials before invoking `GetUsagePlanAsync` method

### Additional Information/Context

SAM Template:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      MethodSettings:
        - LoggingLevel: INFO
          MetricsEnabled: True
          ResourcePath: '/*' # allows for logging on any resource
          HttpMethod: '*' # allows for logging on any method
      Auth:
        ApiKeyRequired: true # sets for all methods
      Models:
        CreateCustomerRequestParameters:
          type: object
          required:
            - CustomerName
            - UsagePlanId
          properties: 
            CustomerName:
              type: string
            UsagePlanId:
              type: string
  CreateCustomer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateCustomerFunction
      Handler: QLDB.API.Config.Lambda::QLDB.API.Config.Lambda.Functions.CreateCustomer.CreateCustomerFunction::FunctionHandler
      Runtime: dotnetcore3.1
      Timeout: 30
      CodeUri: .
      Policies:
        - Statement:
          - Sid: QLDBCreateCustomerCommandPolicy
            Effect: Allow
            Action:
              - apigateway:POST
            Resource: '*'
      Events:
        CreateCustomer:
          Type: Api
          Properties:
            Path: /createCustomer
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
            RequestModel:
              Model: CreateCustomerRequestParameters
              Required: true
              ValidateBody: true

```

### AWS .NET SDK and/or Package version used

AWSSDK.APIGateway 3.7.100.45

### Targeted .NET Platform

.NET Core 3.1,

### Operating System and version

Windows 10
